### ISSUE TITLE
jest测试报错

### ISSUE THREAD

**Issue by kavience** [ant-design/ant-design-icons#355]
项目运行没有问题，在项目中引入 jest 测试，在测试的时候发现，测试虽然通过了，但还是报这个错误。

```js
  console.error
    Error: Uncaught [TypeError: (0 , _insertCss.insertCss) is not a function]
        at reportException (PROJECT_PATH/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
        at invokeEventListeners (PROJECT_PATH/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:209:9)
        at HTMLUnknownElementImpl._dispatch (PROJECT_PATH/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
        at HTMLUnknownElementImpl.dispatchEvent (PROJECT_PATH/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
        at HTMLUnknownElementImpl.dispatchEvent (PROJECT_PATH/node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
        at HTMLUnknownElement.dispatchEvent (PROJECT_PATH/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
        at Object.invokeGuardedCallbackDev (PROJECT_PATH/node_modules/react-dom/cjs/react-dom.development.js:237:16)
        at invokeGuardedCallback (PROJECT_PATH/node_modules/react-dom/cjs/react-dom.development.js:292:31)
        at flushPassiveEffectsImpl (PROJECT_PATH/node_modules/react-dom/cjs/react-dom.development.js:22853:9)
        at unstable_runWithPriority (PROJECT_PATH/node_modules/scheduler/cjs/scheduler.development.js:653:12) TypeError: (0 , _insertCss.insertCss) is not a function
        at PROJECT_PATH/node_modules/@ant-design/icons/lib/utils.js:108:32
        at commitHookEffectListMount (PROJECT_PATH/node_modules/react-dom/cjs/react-dom.development.js:19731:26)
        at commitPassiveHookEffects (PROJECT_PATH/node_modules/react-dom/cjs/react-dom.development.js:19769:11)
        at HTMLUnknownElement.callCallback (PROJECT_PATH/node_modules/react-dom/cjs/react-dom.development.js:188:14)
        at invokeEventListeners (PROJECT_PATH/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
        at HTMLUnknownElementImpl._dispatch (PROJECT_PATH/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
        at HTMLUnknownElementImpl.dispatchEvent (PROJECT_PATH/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
        at HTMLUnknownElementImpl.dispatchEvent (PROJECT_PATH/node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
        at HTMLUnknownElement.dispatchEvent (PROJECT_PATH/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
        at Object.invokeGuardedCallbackDev (PROJECT_PATH/node_modules/react-dom/cjs/react-dom.development.js:237:16)
        at invokeGuardedCallback (PROJECT_PATH/node_modules/react-dom/cjs/react-dom.development.js:292:31)
        at flushPassiveEffectsImpl (PROJECT_PATH/node_modules/react-dom/cjs/react-dom.development.js:22853:9)
        at unstable_runWithPriority (PROJECT_PATH/node_modules/scheduler/cjs/scheduler.development.js:653:12)
        at runWithPriority$1 (PROJECT_PATH/node_modules/react-dom/cjs/react-dom.development.js:11039:10)
        at flushPassiveEffects (PROJECT_PATH/node_modules/react-dom/cjs/react-dom.development.js:22820:12)
        at performSyncWorkOnRoot (PROJECT_PATH/node_modules/react-dom/cjs/react-dom.development.js:21737:3)
        at PROJECT_PATH/node_modules/react-dom/cjs/react-dom.development.js:11089:24
        at unstable_runWithPriority (PROJECT_PATH/node_modules/scheduler/cjs/scheduler.development.js:653:12)
        at runWithPriority$1 (PROJECT_PATH/node_modules/react-dom/cjs/react-dom.development.js:11039:10)
        at flushSyncCallbackQueueImpl (PROJECT_PATH/node_modules/react-dom/cjs/react-dom.development.js:11084:7)
        at flushSyncCallbackQueue (PROJECT_PATH/node_modules/react-dom/cjs/react-dom.development.js:11072:3)
        at scheduleUpdateOnFiber (PROJECT_PATH/node_modules/react-dom/cjs/react-dom.development.js:21199:9)
        at Object.enqueueSetState (PROJECT_PATH/node_modules/react-dom/cjs/react-dom.development.js:12639:5)
        at Notification.Object.<anonymous>.Component.setState (PROJECT_PATH/node_modules/react/cjs/react.development.js:471:16)
        at Notification._this.add (PROJECT_PATH/node_modules/rc-notification/lib/Notification.js:78:13)
        at Object.notice (PROJECT_PATH/node_modules/rc-notification/lib/Notification.js:235:22)
        at PROJECT_PATH/node_modules/antd/lib/message/index.js:96:16
        at getMessageInstance (PROJECT_PATH/node_modules/antd/lib/message/index.js:48:5)
        at PROJECT_PATH/node_modules/antd/lib/message/index.js:95:5
        at new Promise (<anonymous>)
        at Object.notice [as open] (PROJECT_PATH/node_modules/antd/lib/message/index.js:86:22)
        at Object.error (PROJECT_PATH/node_modules/antd/lib/message/index.js:181:16)
        at PROJECT_PATH/src/lib/request/index.ts:22:15
        at processTicksAndRejections (internal/process/task_queues.js:97:5)

      at VirtualConsole.<anonymous> (node_modules/jsdom/lib/jsdom/virtual-console.js:29:45)
      at reportException (node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:70:28)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:209:9)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)

  console.error
    The above error occurred in the <IconReact> component:
        in IconReact (created by AntdIcon)
        in span (created by AntdIcon)
        in AntdIcon (created by ForwardRef(CloseCircleFilled))
        in ForwardRef(CloseCircleFilled)
        in div
        in div (created by Notice)
        in div (created by Notice)
        in Notice (created by Notification)
        in AnimateChild (created by Animate)
        in span (created by Animate)
        in Animate (created by Notification)
        in div (created by Notification)
        in Notification

    Consider adding an error boundary to your tree to customize error handling behavior.
    Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

      at logCapturedError (node_modules/react-dom/cjs/react-dom.development.js:19527:21)
      at logError (node_modules/react-dom/cjs/react-dom.development.js:19564:5)
      at update.callback (node_modules/react-dom/cjs/react-dom.development.js:20708:5)
      at callCallback (node_modules/react-dom/cjs/react-dom.development.js:12490:12)
      at commitUpdateQueue (node_modules/react-dom/cjs/react-dom.development.js:12511:9)
      at commitLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:19883:11)
      at commitLayoutEffects (node_modules/react-dom/cjs/react-dom.development.js:22803:7)

```

**Comment by kavience** [comment]
已找到原因，
```js
// node_modules/@ant-design/icons/lib/utils.js 106行

var useInsertStyles = function useInsertStyles() {
  var styleStr = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : iconStyles;
  (0, _react.useEffect)(function () {
    if (!cssInjectedFlag) {
      (0, _insertCss.insertCss)(styleStr, {
        prepend: true
      });
      cssInjectedFlag = true;
    }
  }) : null;
};
```

查看源代码发现

```js
export const useInsertStyles = (styleStr: string = iconStyles) => {
  useEffect(() => {
    if (!cssInjectedFlag) {
      insertCss(styleStr, {
        prepend: true,
      });
      cssInjectedFlag = true;
    }
  }, []);
};
```

问题出在这里，但我还是不太明白是因为什么？

查看 `insert-css` 库发现，确实没有问题 `insertCss` 本身是一个函数 `[Function: insertCss] { insertCss: [Circular] }`，但是在 jest 测试的时候发现 `_insertCss` 变成了 `{ process: [Function: process] }`，这里要怎么修复呢

**Comment by kavience** [comment]
估计是jest 配置不对，自己再找找其它办法吧
