### ISSUE TITLE
TypeScript: Compilation failed

### ISSUE THREAD

**Issue by ZengTianShengZ** [ant-design/ant-design-icons#469]
执行 yarn vue:ci 报错

```
[es build] replace @ant-design/icons-svg/lib/asn/CloseCircleTwoTone with @ant-design/icons-svg/es/asn/CloseCircleTwoTone
[es build] replace @ant-design/icons-svg/lib/asn/CloseOutlined with @ant-design/icons-svg/es/asn/CloseOutlined
[es build] replace @ant-design/icons-svg/lib/asn/CloseSquareFilled with @ant-design/icons-svg/es/asn/CloseSquareFilled
ant-design-icons-master/packages/icons-vue/node_modules/@vue/runtime-core/dist/runtime-core.d.ts(1346,115): error TS2574: A rest element type must be an array type.
TypeScript: 1 semantic error
TypeScript: emit succeeded (with errors)
TypeScript: 1 semantic error
TypeScript: emit succeeded (with errors)
ant-design-icons-master/packages/icons-vue/node_modules/async-done/index.js:18
    throw err;
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({ uid: 4,
  name: 'es',
  branch: false,
  error:
   { Error: TypeScript: Compilation failed
       at Output.mightFinish (ant-design-icons-master/packages/icons-vue/node_modules/vc-tools/node_modules/gulp-typescript/release/output.js:130:43)
       at applySourceMap.then.appliedSourceMap (ant-design-icons-master/packages/icons-vue/node_modules/vc-tools/node_modules/gulp-typescript/release/output.js:65:22)
     domainEmitter:
      CompileStream {
        _readableState: [ReadableState],
        readable: true,
        domain: [Domain],
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: true,
        allowHalfOpen: true,
        js: [CompileOutputStream],
        dts: [CompileOutputStream],
        project: [Object] },
     domain:
      Domain {
        domain: null,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        members: [],
        [Symbol(kWeak)]: WeakReference {} },
     domainThrown: false },
  duration: [ 36, 729429880 ],
  time: 1615889939945 })
    at Gulp.emit (events.js:187:17)
    at Gulp.EventEmitter.emit (domain.js:448:20)
    at Object.error (ant-design-icons-master/packages/icons-vue/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
    at handler (ant-design-icons-master/packages/icons-vue/node_modules/now-and-later/lib/map.js:50:14)
    at f (ant-design-icons-master/packages/icons-vue/node_modules/once/once.js:25:25)
    at f (ant-design-icons-master/packages/icons-vue/node_modules/once/once.js:25:25)
    at tryCatch (ant-design-icons-master/packages/icons-vue/node_modules/async-done/index.js:24:15)
    at done (ant-design-icons-master/packages/icons-vue/node_modules/async-done/index.js:41:12)
    at Domain.onError (ant-design-icons-master/packages/icons-vue/node_modules/async-done/index.js:52:5)
    at Object.onceWrapper (events.js:286:20)
error Command failed with exit code 1.


```

node -v
v10.21.0
yarn -v
1.22.10

"@ant-design/icons-vue":  "version": "6.0.1"

**Comment by ZengTianShengZ** [comment]
`/packages/icons-vue/tsconfig.json` 添加  skipLibCheck 暂时解决了

```
compilerOptions: {
   "skipLibCheck": true,
   ...
}
```

**Comment by ZengTianShengZ** [comment]
/
