### ISSUE TITLE
Compile error when running with Bun

### ISSUE THREAD

**Issue by AH-dark** [ant-design/ant-design-icons#651]
I use @ant-design/icons 5.3.7 and Bun, and this error occurs when compiling.

```
unhandledRejection /app/xxx/node_modules/@ant-design/icons-svg/es/asn/RightOutlined.js:3
export default RightOutlined;
^^^^^^

SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:128:18)
    at wrapSafe (node:internal/modules/cjs/loader:1280:20)
    at Module._compile (node:internal/modules/cjs/loader:1332:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at mod.require (/app/xxx/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:179:18)
    at 65935 (/app/xxx/.next/server/pages/_app.js:1:289) {
  type: 'SyntaxError'
}
   Collecting page data  .error: script "build" exited with code 1
```

**Comment by afc163** [comment]
Fixed in `@ant-design/icons@5.4.0`: https://github.com/ant-design/ant-design-icons/pull/653
